# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'DS220 Project II'
tagline:          'Data Analysis with Pandas'
description:      'by Paaras Purohit'
baseurl:          /purohitds220proj2/

author:
  name:           'Paaras Purohit'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/PaarasPurohit/purohitds220proj2
